### ISSUE TITLE
story: "Select a stemcell for your BOSH deployment" out of date

### ISSUE THREAD

**Issue by njbennett** [pivotal/cf-onboarding#183] opened 2018-11-06 00:35 UTC
`bosh upload-stemcell https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent?v=VERSION`

should be

`bosh upload-stemcell https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-xenial-go_agent?v=VERSION`

(trusty --> xenial)

**Comment by dsabeti** [comment] 2018-11-15 23:41
This looks like a dupe of this github issue: https://github.com/pivotal-cf/onboarding/issues/179. I'll close this out.

**Closed as completed by dsabeti** 2018-11-15 23:41 UTC
